config("newlib_public") {
    include_dirs = [ "newlib/libc/include" ]

    defines = [
        "NEWLIB_UEFI_CLANG=1",
        "LDBL_EQ_DBL",
        "_LDBL_EQ_DBL",
    ]
}

static_library("c_uefi") {
    sources = [
        "newlib/libc/locale/setlocale.h",
        "newlib/libc/locale/locale.c",
        "newlib/libc/locale/localeconv.c",

        "newlib/libc/stdio/fiprintf.c", 
        "newlib/libc/stdio/fiscanf.c", 
        "newlib/libc/stdio/iprintf.c", 
        "newlib/libc/stdio/iscanf.c", 
        "newlib/libc/stdio/siprintf.c", 
        "newlib/libc/stdio/siscanf.c", 
        "newlib/libc/stdio/sniprintf.c", 
        "newlib/libc/stdio/svfiprintf.c", 
        "newlib/libc/stdio/svfiscanf.c", 
        # newlib/libc/stdio/svfprintf.c 
        "newlib/libc/stdio/svfscanf.c", 
        "newlib/libc/stdio/vdiprintf.c", 
        # newlib/libc/stdio/vfprintf.c 
        "newlib/libc/stdio/vfiprintf.c", 
        "newlib/libc/stdio/vfiscanf.c", 
        "newlib/libc/stdio/vfscanf.c", 
        # newlib/libc/stdio/vfwprintf.c 
        "newlib/libc/stdio/viprintf.c", 
        "newlib/libc/stdio/viscanf.c", 
        "newlib/libc/stdio/vsiprintf.c", 
        "newlib/libc/stdio/vsiscanf.c", 
        "newlib/libc/stdio/vsniprintf.c", 
        "newlib/libc/stdio/sfputs_r.c", 
        "newlib/libc/stdio/sfputws_r.c", 
        "newlib/libc/stdio/sprint_r.c", 
        "newlib/libc/stdio/swprint_r.c", 
        "newlib/libc/stdio/ssputs_r.c", 
        "newlib/libc/stdio/ssputws_r.c", 
        "newlib/libc/stdio/ssprint_r.c", 
        "newlib/libc/stdio/sswprint_r.c", 
        "newlib/libc/stdio/svfiwprintf.c", 
        "newlib/libc/stdio/svfiwscanf.c", 
        # "newlib/libc/stdio/svfwprintf.c", 
        "newlib/libc/stdio/svfwscanf.c", 
        "newlib/libc/stdio/vfiwprintf.c", 
        "newlib/libc/stdio/vfiwscanf.c", 
        "newlib/libc/stdio/vfwscanf.c",
        "newlib/libc/stdio/clearerr.c", 
        "newlib/libc/stdio/fclose.c", 
        "newlib/libc/stdio/fdopen.c", 
        "newlib/libc/stdio/feof.c", 
        "newlib/libc/stdio/ferror.c", 
        "newlib/libc/stdio/fflush.c", 
        "newlib/libc/stdio/fgetc.c", 
        "newlib/libc/stdio/fgetpos.c", 
        "newlib/libc/stdio/fgets.c", 
        "newlib/libc/stdio/fileno.c", 
        "newlib/libc/stdio/findfp.c", 
        "newlib/libc/stdio/flags.c", 
        "newlib/libc/stdio/fopen.c", 
        "newlib/libc/stdio/fprintf.c", 
        "newlib/libc/stdio/fputc.c", 
        "newlib/libc/stdio/fputs.c", 
        "newlib/libc/stdio/fread.c", 
        "newlib/libc/stdio/freopen.c", 
        "newlib/libc/stdio/fscanf.c", 
        "newlib/libc/stdio/fseek.c", 
        "newlib/libc/stdio/fsetpos.c", 
        "newlib/libc/stdio/ftell.c", 
        "newlib/libc/stdio/fvwrite.c", 
        "newlib/libc/stdio/fwalk.c", 
        "newlib/libc/stdio/fwrite.c", 
        "newlib/libc/stdio/getc.c", 
        "newlib/libc/stdio/getchar.c", 
        "newlib/libc/stdio/getc_u.c", 
        "newlib/libc/stdio/getchar_u.c", 
        "newlib/libc/stdio/getdelim.c", 
        "newlib/libc/stdio/getline.c", 
        "newlib/libc/stdio/gets.c", 
        "newlib/libc/stdio/makebuf.c", 
        "newlib/libc/stdio/perror.c", 
        "newlib/libc/stdio/printf.c", 
        "newlib/libc/stdio/putc.c", 
        "newlib/libc/stdio/putchar.c", 
        "newlib/libc/stdio/putc_u.c", 
        "newlib/libc/stdio/putchar_u.c", 
        "newlib/libc/stdio/puts.c", 
        "newlib/libc/stdio/refill.c", 
        "newlib/libc/stdio/remove.c", 
        "newlib/libc/stdio/rename.c", 
        "newlib/libc/stdio/rewind.c", 
        "newlib/libc/stdio/rget.c", 
        "newlib/libc/stdio/scanf.c", 
        "newlib/libc/stdio/sccl.c", 
        "newlib/libc/stdio/setbuf.c", 
        "newlib/libc/stdio/setbuffer.c", 
        "newlib/libc/stdio/setlinebuf.c", 
        "newlib/libc/stdio/setvbuf.c", 
        "newlib/libc/stdio/snprintf.c", 
        "newlib/libc/stdio/sprintf.c", 
        "newlib/libc/stdio/sscanf.c", 
        "newlib/libc/stdio/stdio.c", 
        "newlib/libc/stdio/tmpfile.c", 
        "newlib/libc/stdio/tmpnam.c", 
        "newlib/libc/stdio/ungetc.c", 
        "newlib/libc/stdio/vdprintf.c", 
        "newlib/libc/stdio/vprintf.c", 
        "newlib/libc/stdio/vscanf.c", 
        "newlib/libc/stdio/vsnprintf.c", 
        "newlib/libc/stdio/vsprintf.c", 
        "newlib/libc/stdio/vsscanf.c", 
        "newlib/libc/stdio/wbuf.c", 
        "newlib/libc/stdio/wbufw.c", 
        "newlib/libc/stdio/wsetup.c",

        "newlib/libc/stdlib/__adjust.c", 
        "newlib/libc/stdlib/__atexit.c", 
        "newlib/libc/stdlib/__call_atexit.c", 
        "newlib/libc/stdlib/__exp10.c", 
        "newlib/libc/stdlib/__ten_mu.c", 
        "newlib/libc/stdlib/_Exit.c", 
        "newlib/libc/stdlib/abort.c", 
        "newlib/libc/stdlib/abs.c", 
        "newlib/libc/stdlib/aligned_alloc.c", 
        "newlib/libc/stdlib/assert.c", 
        "newlib/libc/stdlib/atexit.c", 
        "newlib/libc/stdlib/atof.c", 
        "newlib/libc/stdlib/atoff.c", 
        "newlib/libc/stdlib/atoi.c", 
        "newlib/libc/stdlib/atol.c", 
        "newlib/libc/stdlib/calloc.c", 
        "newlib/libc/stdlib/div.c", 
        "newlib/libc/stdlib/dtoa.c", 
        "newlib/libc/stdlib/dtoastub.c", 
        "newlib/libc/stdlib/environ.c", 
        "newlib/libc/stdlib/envlock.c", 
        "newlib/libc/stdlib/eprintf.c", 
        "newlib/libc/stdlib/exit.c", 
        "newlib/libc/stdlib/gdtoa-gethex.c", 
        "newlib/libc/stdlib/gdtoa-hexnan.c", 
        "newlib/libc/stdlib/getenv.c", 
        "newlib/libc/stdlib/getenv_r.c", 
        "newlib/libc/stdlib/imaxabs.c", 
        "newlib/libc/stdlib/imaxdiv.c", 
        "newlib/libc/stdlib/itoa.c", 
        "newlib/libc/stdlib/labs.c", 
        "newlib/libc/stdlib/ldiv.c", 
        "newlib/libc/stdlib/ldtoa.c", 
        "newlib/libc/stdlib/gdtoa-ldtoa.c", 
        "newlib/libc/stdlib/gdtoa-gdtoa.c", 
        "newlib/libc/stdlib/gdtoa-dmisc.c", 
        "newlib/libc/stdlib/gdtoa-gmisc.c", 
        "newlib/libc/stdlib/malloc.c", 
        "newlib/libc/stdlib/mblen.c", 
        "newlib/libc/stdlib/mblen_r.c", 
        "newlib/libc/stdlib/mbstowcs.c", 
        "newlib/libc/stdlib/mbstowcs_r.c", 
        "newlib/libc/stdlib/mbtowc.c", 
        "newlib/libc/stdlib/mbtowc_r.c", 
        "newlib/libc/stdlib/mlock.c", 
        "newlib/libc/stdlib/mprec.c", 
        "newlib/libc/stdlib/mstats.c", 
        "newlib/libc/stdlib/on_exit_args.c", 
        "newlib/libc/stdlib/quick_exit.c", 
        "newlib/libc/stdlib/rand.c", 
        "newlib/libc/stdlib/rand_r.c", 
        "newlib/libc/stdlib/random.c", 
        "newlib/libc/stdlib/realloc.c", 
        "newlib/libc/stdlib/reallocarray.c", 
        "newlib/libc/stdlib/reallocf.c", 
        "newlib/libc/stdlib/sb_charsets.c", 
        "newlib/libc/stdlib/strtod.c", 
        "newlib/libc/stdlib/strtoimax.c", 
        "newlib/libc/stdlib/strtol.c", 
        "newlib/libc/stdlib/strtoul.c", 
        "newlib/libc/stdlib/strtoumax.c", 
        "newlib/libc/stdlib/utoa.c", 
        "newlib/libc/stdlib/wcstod.c", 
        "newlib/libc/stdlib/wcstoimax.c", 
        "newlib/libc/stdlib/wcstol.c", 
        "newlib/libc/stdlib/wcstoul.c", 
        "newlib/libc/stdlib/wcstoumax.c", 
        "newlib/libc/stdlib/wcstombs.c", 
        "newlib/libc/stdlib/wcstombs_r.c", 
        "newlib/libc/stdlib/wctomb.c", 
        "newlib/libc/stdlib/wctomb_r.c",

        "newlib/libc/string/bcopy.c", 
        "newlib/libc/string/bzero.c", 
        "newlib/libc/string/explicit_bzero.c", 
        "newlib/libc/string/ffsl.c", 
        "newlib/libc/string/ffsll.c", 
        "newlib/libc/string/fls.c", 
        "newlib/libc/string/flsl.c", 
        "newlib/libc/string/flsll.c", 
        "newlib/libc/string/index.c", 
        "newlib/libc/string/memchr.c", 
        "newlib/libc/string/memcmp.c", 
        "newlib/libc/string/memcpy.c", 
        "newlib/libc/string/memmove.c", 
        "newlib/libc/string/memset.c", 
        "newlib/libc/string/rindex.c", 
        "newlib/libc/string/strcasecmp.c", 
        "newlib/libc/string/strcat.c", 
        "newlib/libc/string/strchr.c", 
        "newlib/libc/string/strcmp.c", 
        "newlib/libc/string/strcoll.c", 
        "newlib/libc/string/strcpy.c", 
        "newlib/libc/string/strcspn.c", 
        "newlib/libc/string/strdup.c", 
        "newlib/libc/string/strdup_r.c", 
        "newlib/libc/string/strerror.c", 
        "newlib/libc/string/strerror_r.c", 
        "newlib/libc/string/strlcat.c", 
        "newlib/libc/string/strlcpy.c", 
        "newlib/libc/string/strlen.c",  
        "newlib/libc/string/strlwr.c", 
        "newlib/libc/string/strncasecmp.c", 
        "newlib/libc/string/strncat.c", 
        "newlib/libc/string/strncmp.c", 
        "newlib/libc/string/strncpy.c", 
        "newlib/libc/string/strnlen.c", 
        "newlib/libc/string/strnstr.c", 
        "newlib/libc/string/strpbrk.c", 
        "newlib/libc/string/strrchr.c", 
        "newlib/libc/string/strsep.c", 
        "newlib/libc/string/strsignal.c", 
        "newlib/libc/string/strspn.c", 
        "newlib/libc/string/strtok.c", 
        "newlib/libc/string/strtok_r.c", 
        "newlib/libc/string/strupr.c", 
        "newlib/libc/string/strxfrm.c",  
        "newlib/libc/string/strstr.c", 
        "newlib/libc/string/swab.c", 
        "newlib/libc/string/timingsafe_bcmp.c", 
        "newlib/libc/string/timingsafe_memcmp.c", 
        "newlib/libc/string/u_strerr.c", 
        "newlib/libc/string/wcscat.c", 
        "newlib/libc/string/wcschr.c", 
        "newlib/libc/string/wcscmp.c", 
        "newlib/libc/string/wcscoll.c", 
        "newlib/libc/string/wcscpy.c", 
        "newlib/libc/string/wcscspn.c", 
        "newlib/libc/string/wcslcat.c", 
        "newlib/libc/string/wcslcpy.c", 
        "newlib/libc/string/wcslen.c", 
        "newlib/libc/string/wcsncat.c", 
        "newlib/libc/string/wcsncmp.c", 
        "newlib/libc/string/wcsncpy.c", 
        "newlib/libc/string/wcsnlen.c", 
        "newlib/libc/string/wcspbrk.c", 
        "newlib/libc/string/wcsrchr.c", 
        "newlib/libc/string/wcsspn.c", 
        "newlib/libc/string/wcsstr.c", 
        "newlib/libc/string/wcstok.c", 
        "newlib/libc/string/wcswidth.c", 
        "newlib/libc/string/wcsxfrm.c", 
        "newlib/libc/string/wcwidth.c", 
        "newlib/libc/string/wmemchr.c", 
        "newlib/libc/string/wmemcmp.c", 
        "newlib/libc/string/wmemcpy.c", 
        "newlib/libc/string/wmemmove.c", 
        "newlib/libc/string/wmemset.c", 
        "newlib/libc/string/xpg_strerror_r.c",
    ]

    configs = [
        "//build/config:freestanding_x64",
        "//build/config:warnings"
    ]

    public_configs = [":newlib_public"]

    check_includes = false
}